Modifies util::load_private_key to support PKCS8, adds tests
SergioBenitez/hyper-rustls pull request #1
Opened 2017-05-15 03:11 UTC by peterdelevoryas

Currently, `util::load_private_key` does
not handle the modern private key format,
PKCS8. `rustls` provides a utility for
reading PKCS8 formatted private keys,
this commit modifies `load_private_key`
to first attempt reading one PKCS8 key,
or else one RSA key. This is the behavior
used in the `rustls` [tls server](https://github.com/ctz/rustls/blob/master/examples/tlsserver.rs) example.

This commit also includes two private key
files, one formatted in the traditional
RSA format, one in the PKCS8 format,
and adds tests for loading each one.

2017-05-20 01:16 UTC, SergioBenitez requested changes
This is great. We should definitely accept both PKCS#1 (`BEGIN RSA PRIVATE KEY`) and PKCS#8 (`BEGIN PRIVATE KEY`) PEM files. A few changes and we'll get this in.

2017-05-20 01:16 UTC, SergioBenitez commented on src/lib.rs
> +            .or_else(|_| {
This `or_else` will called if reading/parsing a PKCS#8 file succeeds but `expect_one` fails. We probably don't want to try to read the file again in this case.

2017-05-20 01:16 UTC, SergioBenitez commented on src/lib.rs
> +        fn expect_one(mut keys: Vec<rustls::PrivateKey>) -> Result<rustls::PrivateKey> {
`expect` usually implies that a `panic!` might take place. Let's rename this to `take_one` or something of that sort.

2017-05-20 01:16 UTC, SergioBenitez commented on src/lib.rs
> +        let start = io::SeekFrom::Start(0);
We only use this variable once, so we can probably just inline the `io::SeekFrom::Start(0)` at that location.

2017-05-21 04:56 UTC, SergioBenitez requested changes
This looks great! Just a couple of stylistic changes. :)

2017-05-21 04:56 UTC, SergioBenitez commented on src/lib.rs
> +        let private_keys_fn = {
Can you add a comment about why this is happening here, for future reference? Just something short and pithy, nor more than a couple of lines.

2017-05-21 04:56 UTC, SergioBenitez commented on src/lib.rs
> +            reader.seek(io::SeekFrom::Start(0)).map_err(Error::Io)?;
Let's add an empty line above here.

2017-05-21 07:10 UTC, peterdelevoryas commented on src/lib.rs
> +            reader.seek(io::SeekFrom::Start(0)).map_err(Error::Io)?;
I actually went a couple steps further and that part, making another nested block and making the match statement the final expression for `private_keys_fn`. Sorry about that, if it's too much I can change it back to what it was.

2017-05-21 08:59 UTC, SergioBenitez commented on src/lib.rs
> +            reader.seek(io::SeekFrom::Start(0)).map_err(Error::Io)?;
Why do we need any nested blocks at all? Can we just do:

```rust
let mut first_line = String::new();
reader.read_line(&mut line).map_err(Error::Io)?;
reader.seek(io::SeekFrom::Start(0)).map_err(Error::Io)?;

let private_keys_fn = match first_line.trim_right() {
    "-----BEGIN RSA PRIVATE KEY-----" => pemfile::rsa_private_keys,
    "-----BEGIN PRIVATE KEY-----" => pemfile::pkcs8_private_keys,
    _ => return Err(Error::BadKey)
};
``

2017-05-21 10:56 UTC, peterdelevoryas commented on src/lib.rs
> +            reader.seek(io::SeekFrom::Start(0)).map_err(Error::Io)?;
No reason at all, and I prefer what you wrote! I'm going to amend the revision.

2017-05-24 22:54 UTC, SergioBenitez approved these changes

2017-05-24 22:55 UTC, merged